#!/usr/bin/env bash
# ============================================================================
# Mova VPS bootstrap — one-shot setup for a fresh Ubuntu/Debian box.
# ============================================================================
#
# What this does (in order):
#
#   1. Update apt, install: docker, docker compose plugin, nginx, certbot,
#      git, ufw, postgresql-client (for pg_dump), rclone (optional B2 sync).
#   2. Create unprivileged `mova` user, add to docker group.
#   3. Clone the repo to /opt/mova (or pull if present).
#   4. Place .env at /opt/mova/.env — operator MUST edit it before
#      `docker compose up`.
#   5. Drop the nginx site config + reload nginx.
#   6. Run certbot --nginx for the domain (interactive — operator
#      provides email).
#   7. Install systemd unit `mova.service` so docker compose comes
#      up automatically on reboot.
#   8. Install backups cron + log rotation.
#   9. Tighten ufw: allow 22, 80, 443 only.
#
# Idempotent — safe to re-run after a partial failure. Each step
# checks for "already done" markers before doing destructive work.
#
# Usage on a fresh Ubuntu 22.04 / 24.04 box (root user):
#
#   curl -fsSL https://raw.githubusercontent.com/XXXDoriXXX/MOVA/master/infra/vps/bootstrap.sh \
#     -o /tmp/mova-bootstrap.sh
#   chmod +x /tmp/mova-bootstrap.sh
#   MOVA_DOMAIN=api.example.com \
#   MOVA_ADMIN_EMAIL=admin@example.com \
#     /tmp/mova-bootstrap.sh
#
# Required env:
#   MOVA_DOMAIN       — DNS A record must point to this VPS first.
#   MOVA_ADMIN_EMAIL  — passed to certbot for Let's Encrypt notifications.
# Optional:
#   MOVA_REPO         — defaults to https://github.com/XXXDoriXXX/MOVA.git
#   MOVA_BRANCH       — defaults to master
# ============================================================================
set -euo pipefail

# ── Inputs / defaults ───────────────────────────────────────────
: "${MOVA_DOMAIN:?Set MOVA_DOMAIN=api.example.com}"
: "${MOVA_ADMIN_EMAIL:?Set MOVA_ADMIN_EMAIL=you@example.com}"
MOVA_REPO="${MOVA_REPO:-https://github.com/XXXDoriXXX/MOVA.git}"
MOVA_BRANCH="${MOVA_BRANCH:-master}"
MOVA_HOME="/opt/mova"
MOVA_USER="mova"

log() { echo -e "\n\033[1;36m▶ $*\033[0m"; }
die() { echo -e "\n\033[1;31m✗ $*\033[0m" >&2; exit 1; }

# Must run as root (or with sudo). Most steps need privileged ops.
[ "$(id -u)" -eq 0 ] || die "Run as root (sudo $0)"

# ── 1. apt packages ─────────────────────────────────────────────
log "Installing system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl gnupg lsb-release \
  git nginx ufw postgresql-client-16 \
  python3-certbot-nginx rclone

# Docker (official convenience script — simpler than maintaining apt repos here)
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi

# Docker compose plugin should be included by the Docker install above
# (compose-plugin). Verify.
docker compose version >/dev/null 2>&1 || die "docker compose plugin missing"

# ── 2. mova user ────────────────────────────────────────────────
if ! id "$MOVA_USER" >/dev/null 2>&1; then
  log "Creating $MOVA_USER user..."
  useradd -m -s /bin/bash "$MOVA_USER"
fi
usermod -aG docker "$MOVA_USER"

# ── 3. clone repo ───────────────────────────────────────────────
if [ ! -d "$MOVA_HOME/.git" ]; then
  log "Cloning $MOVA_REPO → $MOVA_HOME ..."
  mkdir -p "$(dirname "$MOVA_HOME")"
  sudo -u "$MOVA_USER" git clone --branch "$MOVA_BRANCH" --depth 1 "$MOVA_REPO" "$MOVA_HOME"
else
  log "Pulling latest from $MOVA_BRANCH ..."
  sudo -u "$MOVA_USER" git -C "$MOVA_HOME" fetch --depth 1 origin "$MOVA_BRANCH"
  sudo -u "$MOVA_USER" git -C "$MOVA_HOME" reset --hard "origin/$MOVA_BRANCH"
fi
chown -R "$MOVA_USER:$MOVA_USER" "$MOVA_HOME"

# ── 4. .env scaffold (operator must edit) ───────────────────────
if [ ! -f "$MOVA_HOME/.env" ]; then
  log ".env missing — creating empty stub. EDIT IT BEFORE STARTING THE STACK."
  install -m 600 -o "$MOVA_USER" -g "$MOVA_USER" /dev/null "$MOVA_HOME/.env"
  cat >"$MOVA_HOME/.env" <<EOF
# Mova production .env — fill before running docker compose up.
# Generated by infra/vps/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).

NODE_ENV=production
PORT=3000

# Database (Neon or self-hosted)
DATABASE_URL=
DATABASE_SSL=true

# Redis (managed or compose)
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=

# Auth
JWT_SECRET=
ADMIN_PASSWORD=
SETTINGS_ENCRYPTION_KEY=

# LiveKit
LIVEKIT_URL=
LIVEKIT_API_KEY=
LIVEKIT_API_SECRET=
SIP_TRUNK_ID=

# Providers
OPENAI_API_KEY=
DEEPGRAM_API_KEY=
GOOGLE_TTS_API_KEY=
ELEVENLABS_API_KEY=
GOOGLE_GENERATIVE_AI_API_KEY=
TTS_PROVIDER=google
TTS_FALLBACK_PROVIDER=gemini
GOOGLE_TTS_VOICE=uk-UA-Chirp3-HD-Despina

# Observability
SENTRY_DSN=
GRAFANA_ADMIN_PASSWORD=
EOF
fi

# ── 5. nginx site ───────────────────────────────────────────────
log "Installing nginx site config for $MOVA_DOMAIN ..."
NGINX_AVAILABLE=/etc/nginx/sites-available/mova
NGINX_ENABLED=/etc/nginx/sites-enabled/mova
sed "s/__MOVA_DOMAIN__/$MOVA_DOMAIN/g" \
  "$MOVA_HOME/infra/vps/nginx/mova.conf.template" >"$NGINX_AVAILABLE"
ln -sf "$NGINX_AVAILABLE" "$NGINX_ENABLED"

# Seed the active-upstream include file with the default blue port.
# switch-color.sh rewrites this file on every blue-green deploy.
# Default to blue = 3000 so a fresh install runs single-color out of
# the box; the operator can opt into blue-green later by running
# `IMAGE_TAG=<sha> infra/vps/switch-color.sh` once green is built.
mkdir -p /etc/nginx/conf.d
cat >/etc/nginx/conf.d/mova-active-upstream.conf <<'EOF'
# Default upstream — managed by infra/vps/switch-color.sh in
# blue-green deployments. Edit by hand at your own risk.
upstream mova_api {
    server 127.0.0.1:3000;
    keepalive 32;
}
EOF
# Track which color is "active" so the switch script's compare is fast.
echo blue > "$MOVA_HOME/.active-color"
chown "$MOVA_USER:$MOVA_USER" "$MOVA_HOME/.active-color"
# Disable the default site that ships with nginx — it would fight ours on :80.
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx || systemctl start nginx

# ── 6. TLS via certbot (interactive) ────────────────────────────
if [ ! -d "/etc/letsencrypt/live/$MOVA_DOMAIN" ]; then
  log "Provisioning TLS cert for $MOVA_DOMAIN ..."
  certbot --nginx \
    -d "$MOVA_DOMAIN" \
    --non-interactive --agree-tos \
    --email "$MOVA_ADMIN_EMAIL" \
    --redirect
else
  log "TLS cert exists — skipping certbot."
fi

# ── 7. systemd unit ─────────────────────────────────────────────
log "Installing systemd unit mova.service ..."
sed "s|__MOVA_HOME__|$MOVA_HOME|g" \
  "$MOVA_HOME/infra/vps/systemd/mova.service.template" \
  >/etc/systemd/system/mova.service
systemctl daemon-reload
systemctl enable mova.service

# ── 8. backups cron ─────────────────────────────────────────────
log "Installing pg_dump cron + restore-drill cron ..."
install -m 755 \
  "$MOVA_HOME/infra/vps/cron/pg-backup.sh" \
  /usr/local/bin/mova-pg-backup
install -m 755 \
  "$MOVA_HOME/infra/vps/cron/restore-drill.sh" \
  /usr/local/bin/mova-restore-drill
mkdir -p /var/backups/mova
chown "$MOVA_USER:$MOVA_USER" /var/backups/mova
# Crontab:
#   * Daily backup at 03:30 UTC.
#   * Monthly restore-drill on the 7th at 04:00 UTC — a week into
#     the month so we always have ≥1 fresh daily dump to test against,
#     and on a Sunday-ish offset that doesn't collide with a typical
#     "first-of-month report" workload.
#   systemd-timer would be more polished but cron is universal and
#   easier to inspect with `crontab -l`. Replace the whole crontab
#   atomically so re-running bootstrap doesn't duplicate entries.
CRON_TMP=$(mktemp)
{
  # Preserve any non-mova lines the operator may have added by hand.
  crontab -u "$MOVA_USER" -l 2>/dev/null \
    | grep -vE 'mova-pg-backup|mova-restore-drill' || true
  echo "30 3 * * * /usr/local/bin/mova-pg-backup >> /var/log/mova-backup.log 2>&1"
  echo "0 4 7 * * /usr/local/bin/mova-restore-drill >> /var/log/mova-restore-drill.log 2>&1"
} > "$CRON_TMP"
crontab -u "$MOVA_USER" "$CRON_TMP"
rm "$CRON_TMP"

# Log rotation for backup + restore-drill logs.
cat >/etc/logrotate.d/mova <<'EOF'
/var/log/mova-backup.log /var/log/mova-restore-drill.log {
    weekly
    rotate 8
    compress
    missingok
    notifempty
    create 0640 mova mova
}
EOF

# ── 9. firewall ─────────────────────────────────────────────────
log "Configuring ufw ..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment 'ssh'
ufw allow 80/tcp comment 'http'
ufw allow 443/tcp comment 'https'
ufw --force enable

# ── Done ─────────────────────────────────────────────────────────
log "Bootstrap complete."
cat <<EOF

NEXT STEPS (manual, on this box):
  1. EDIT  $MOVA_HOME/.env  with real credentials.
  2. sudo systemctl start mova.service
  3. sudo journalctl -u mova.service -f      # follow boot
  4. Verify: curl https://$MOVA_DOMAIN/v1/health/live
  5. Grafana: bind-mounted to 127.0.0.1:3030 — SSH tunnel or expose
     via a separate nginx vhost with basic-auth (see infra/README.md).

Backups: nightly to /var/backups/mova. To enable off-site sync, edit
/usr/local/bin/mova-pg-backup and uncomment the rclone block.
EOF
