#!/usr/bin/env bash
# ============================================================================
# Zero-downtime blue-green deploy: switch nginx's api-gateway upstream
# from the active color to the inactive one.
# ============================================================================
#
# Usage (on the VPS, as the mova user):
#   IMAGE_TAG=<sha> ./infra/vps/switch-color.sh
#
# Algorithm:
#   1. Read /opt/mova/.active-color → "blue" | "green" (default "blue").
#   2. Compute the inactive color (the target of the deploy).
#   3. docker compose pull + up -d the inactive color with the new IMAGE_TAG.
#   4. Poll the inactive color's /health/live until 200 or 60s timeout.
#   5. Rewrite /etc/nginx/conf.d/mova-active-upstream.conf to point at
#      the inactive color, nginx -s reload.
#   6. Flip /opt/mova/.active-color to the new color.
#   7. (Optional) stop the previously-active container after a 10s
#      drain so any in-flight request finishes.
#
# Idempotent — re-running with the same IMAGE_TAG re-deploys the
# inactive color, useful for forcing a redeploy.
#
# Rollback: just run again with the previous IMAGE_TAG. The "previous"
# tag is logged to /opt/mova/.previous-color-tag on every successful
# switch.
# ============================================================================
set -euo pipefail

MOVA_HOME="${MOVA_HOME:-/opt/mova}"
ACTIVE_FILE="$MOVA_HOME/.active-color"
PREV_TAG_FILE="$MOVA_HOME/.previous-color-tag"
UPSTREAM_CONF="/etc/nginx/conf.d/mova-active-upstream.conf"
HEALTH_TIMEOUT_SEC=60
DRAIN_DELAY_SEC=10

: "${IMAGE_TAG:?Set IMAGE_TAG=<git-sha>}"
GHCR_OWNER="${GHCR_OWNER:-$(echo "$(git -C "$MOVA_HOME" remote get-url origin)" | sed -nE 's#.*github.com[:/]([^/]+)/.*#\L\1#p')}"
export GHCR_OWNER IMAGE_TAG

log() { echo -e "\n\033[1;36m▶ $*\033[0m"; }
die() { echo -e "\n\033[1;31m✗ $*\033[0m" >&2; exit 1; }

# ── 1. Determine active + target ───────────────────────────────
active="$(cat "$ACTIVE_FILE" 2>/dev/null || echo blue)"
case "$active" in
  blue)  target=green; active_port=3000; target_port=3010 ;;
  green) target=blue;  active_port=3010; target_port=3000 ;;
  *)     die "unknown active color '$active' in $ACTIVE_FILE" ;;
esac
log "Active=$active (port $active_port) → Target=$target (port $target_port)"

# Save the currently-deployed tag for the active color so we can
# rollback to it without git-archaeology.
current_tag=$(docker inspect -f '{{.Config.Image}}' "mova_api_gateway_$active" 2>/dev/null | awk -F: '{print $NF}' || echo "")
[ -n "$current_tag" ] && echo "$current_tag" > "$PREV_TAG_FILE"

# ── 2. Deploy the inactive color ───────────────────────────────
COMPOSE_FILES=(
  -f "$MOVA_HOME/docker-compose.yml"
  -f "$MOVA_HOME/docker-compose.prod.yml"
  -f "$MOVA_HOME/docker-compose.bluegreen.yml"
)
log "Pulling new image for $target ..."
docker compose "${COMPOSE_FILES[@]}" pull --quiet "api-gateway-$target"
log "Starting api-gateway-$target ..."
docker compose "${COMPOSE_FILES[@]}" up -d --no-deps "api-gateway-$target"

# ── 3. Healthcheck poll ────────────────────────────────────────
log "Waiting for api-gateway-$target /health/live ..."
deadline=$(( $(date +%s) + HEALTH_TIMEOUT_SEC ))
ok=0
while [ "$(date +%s)" -lt "$deadline" ]; do
  if curl -fsS -m 3 "http://127.0.0.1:${target_port}/health/live" >/dev/null 2>&1; then
    ok=1
    break
  fi
  sleep 2
done
[ "$ok" -eq 1 ] || {
  log "Target $target failed health within ${HEALTH_TIMEOUT_SEC}s — NOT switching nginx. Logs:"
  docker logs --tail=50 "mova_api_gateway_$target" || true
  die "Deploy aborted; $active is still serving."
}

# ── 4. Switch nginx upstream ───────────────────────────────────
log "Rewriting nginx upstream → $target (port $target_port)"
cat >"$UPSTREAM_CONF" <<EOF
# Auto-generated by switch-color.sh on $(date -u +%FT%TZ).
# Active color: $target
upstream mova_api {
    server 127.0.0.1:${target_port};
    keepalive 32;
}
EOF
nginx -t
nginx -s reload

# ── 5. Persist active color + drain old ────────────────────────
echo "$target" > "$ACTIVE_FILE"
log "Active color is now $target. Draining $active in ${DRAIN_DELAY_SEC}s ..."
sleep "$DRAIN_DELAY_SEC"
docker compose "${COMPOSE_FILES[@]}" stop "api-gateway-$active" || true

log "Switch complete. Rollback: IMAGE_TAG=$(cat "$PREV_TAG_FILE" 2>/dev/null || echo '?') $0"
