import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';

import { Conversation } from './conversation.entity';

export enum MessageRole {
  /** Speech-to-text result of the person on the other end of the line. */
  INTERLOCUTOR = 'interlocutor',
  /** Generated by the LLM. */
  AI = 'ai',
  /** Typed by the user (or accepted suggestion) and TTS-spoken on their behalf. */
  USER_TYPED = 'user_typed',
  /** System-level event (call started, model swapped, etc.) for transcript context. */
  SYSTEM = 'system',
}

export enum TtsStatus {
  COMPLETED = 'completed',
  INTERRUPTED = 'interrupted',
  FAILED = 'failed',
}

/**
 * A single message in the conversation transcript.
 *
 * Mobile UX:
 *   - Rendered as chat bubbles. The role determines alignment and color.
 *   - `ttsStatus='interrupted'` is shown with a "(перервано)" tag.
 *   - `llmProvider`/`llmModel` exposed in detail view so users can see WHICH
 *     model answered which turn (helps debug "the AI was weird at message 12").
 *
 * Write path:
 *   - INSERT only. Updates are limited to `ttsStatus` flipping
 *     `completed → interrupted` when the user stops TTS mid-utterance.
 *   - Persisted from agent-worker on `transcript.final` / `ai.text.final` /
 *     user.speak / user.accept_suggestion events.
 *
 * Scaling:
 *   - At >100M rows we'll partition by `(conversationId)` hash or by
 *     `createdAt` month. The (conversationId, createdAt) index keeps history
 *     queries fast at any size.
 */
@Entity('messages')
@Index('idx_messages_conversation_created', ['conversationId', 'createdAt'])
export class Message {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  conversationId!: string;

  @ManyToOne(() => Conversation, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'conversationId' })
  conversation!: Conversation;

  @Column({ type: 'enum', enum: MessageRole })
  role!: MessageRole;

  @Column({ type: 'text' })
  content!: string;

  /** Null for INTERLOCUTOR/SYSTEM (TTS only applies to spoken messages). */
  @Column({ type: 'enum', enum: TtsStatus, nullable: true })
  ttsStatus!: TtsStatus | null;

  /** Provider that produced this message. Null for INTERLOCUTOR. */
  @Column({ type: 'varchar', length: 50, nullable: true })
  llmProvider!: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true })
  llmModel!: string | null;

  @Column({ type: 'varchar', length: 50, nullable: true })
  ttsProvider!: string | null;

  @Column({ type: 'varchar', length: 100, nullable: true })
  ttsVoice!: string | null;

  /** TTS playback duration in ms; null when not applicable / not measured. */
  @Column({ type: 'int', nullable: true })
  durationMs!: number | null;

  @CreateDateColumn()
  createdAt!: Date;
}
