import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';

import { User } from './user.entity';

export enum PaymentEventStatus {
  SUCCESS = 'success',
  FAILED = 'failed',
  REFUNDED = 'refunded',
  PENDING = 'pending',
}

/**
 * Idempotent payment event log. One row per webhook from LiqPay/Stripe/etc.
 *
 * Two distinct idempotency mechanisms — they protect against different
 * sources of duplicates:
 *
 *   - `externalId` (provider-side): the provider's payment id (LiqPay's
 *     `payment_id`, Stripe's `pi_xxx`). UNIQUE blocks the **provider** from
 *     double-processing if it retries the webhook to us — common scenario.
 *
 *   - `idempotencyKey` (client-side): a UUID the mobile client generates
 *     before the user taps "topup". Sent as `Idempotency-Key` header. If
 *     the request times out mid-flight and the client retries, we recognise
 *     the same key and return the original PaymentEvent instead of charging
 *     twice. UNIQUE composite on (userId, idempotencyKey) — the same key
 *     across users is fine (they're independent ledgers).
 *
 *     NULLs are distinct in Postgres UNIQUE indexes by default, so calls
 *     made without an idempotency key (server-driven topups, legacy clients)
 *     coexist freely.
 *
 * Reconciliation: a daily cron compares our `success` rows against the
 * provider's API to catch missed webhooks (rare but happens). See Phase 12.6.
 *
 * payload: stores the raw webhook JSON for forensic / dispute support. Capped
 * by Postgres jsonb soft limit (≈ 256MB); in practice payloads are < 4KB.
 */
@Entity('payment_events')
@Index('idx_payment_external_id', ['externalId'], { unique: true })
@Index('idx_payment_user_idempotency', ['userId', 'idempotencyKey'], {
  unique: true,
  where: '"idempotencyKey" IS NOT NULL',
})
@Index('idx_payment_user_created', ['userId', 'createdAt'])
export class PaymentEvent {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Column({ type: 'uuid' })
  userId!: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'userId' })
  user!: User;

  /** Provider's idempotency key (payment_id from webhook). */
  @Column({ type: 'varchar', length: 255 })
  externalId!: string;

  /**
   * Client-side idempotency key — typically a UUIDv4 generated by the mobile
   * app and sent in the `Idempotency-Key` header on POST /billing/topup.
   * NULL when the call originates server-side (cron, admin tools).
   */
  @Column({ type: 'varchar', length: 64, nullable: true })
  idempotencyKey!: string | null;

  @Column({ type: 'int' })
  amountCents!: number;

  @Column({ type: 'char', length: 3, default: 'UAH' })
  currency!: string;

  @Column({ type: 'enum', enum: PaymentEventStatus })
  status!: PaymentEventStatus;

  /** Raw webhook body for forensics. */
  @Column({ type: 'jsonb' })
  payload!: Record<string, unknown>;

  /** Set when our handler finishes (success or terminal failure). */
  @Column({ type: 'timestamptz', nullable: true })
  processedAt!: Date | null;

  @CreateDateColumn()
  createdAt!: Date;
}
