import {
  BadRequestException,
  Body,
  Controller,
  Get,
  Header,
  Headers,
  HttpCode,
  HttpStatus,
  Post,
  Query,
} from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiTags } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';

import { CurrentUser, Public, type AuthenticatedUser } from '@mova-back/shared-auth';
import type { PaymentEvent, Plan, UsageRecord } from '@mova-back/shared-database';

import { BillingService, type BillingSummary } from './billing.service';
import { SubscribeDto, TopupDto } from './dto/billing.schemas';

const IDEMPOTENCY_KEY_RE = /^[\x20-\x7E]{1,64}$/;

@ApiTags('billing')
@ApiBearerAuth()
@Controller('billing')
export class BillingController {
  constructor(private readonly billing: BillingService) {}

  @Get('me')
  @ApiOperation({ summary: 'Get current subscription + balance summary' })
  me(@CurrentUser() user: AuthenticatedUser): Promise<BillingSummary> {
    return this.billing.getSummary(user.id);
  }

  @Get('plans')
  @ApiOperation({ summary: 'List active plans available for subscription' })
  async listPlans(): Promise<{ items: Plan[] }> {
    return { items: await this.billing.listPlans() };
  }

  @Get('usage')
  @ApiOperation({ summary: 'List recent usage records (last 13 months)' })
  async listUsage(
    @CurrentUser() user: AuthenticatedUser,
    @Query('from') from?: string,
    @Query('to') to?: string,
  ): Promise<{ items: UsageRecord[] }> {
    const fromDate = from ? new Date(from) : undefined;
    const toDate = to ? new Date(to) : undefined;
    return { items: await this.billing.listUsage(user.id, fromDate, toDate) };
  }

  @Post('topup')
  @HttpCode(HttpStatus.OK)
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  @ApiOperation({
    summary: 'Start a wallet top-up — returns a provider checkout URL',
  })
  @ApiHeader({
    name: 'Idempotency-Key',
    required: true,
    description:
      'UUID/opaque token (≤64 printable ASCII) generated by the client before ' +
      'the first attempt. Resubmitting the same key returns the same checkout ' +
      'without creating a second pending payment.',
  })
  async topup(
    @CurrentUser() user: AuthenticatedUser,
    @Body() dto: TopupDto,
    @Headers('idempotency-key') idempotencyKeyHeader?: string,
  ): Promise<{
    paymentEventId: string;
    balanceCents: number;
    paymentUrl: string;
    reused: boolean;
  }> {
    const idempotencyKey = this.parseIdempotencyKey(idempotencyKeyHeader);
    // Require the key: a keyless top-up has no dedup, so a double-tap or a
    // network retry creates two pending payments. The client always sends one.
    if (!idempotencyKey) {
      throw new BadRequestException(
        'Idempotency-Key header is required for top-ups',
      );
    }
    const { paymentEventId, checkoutUrl, reused } = await this.billing.startTopup(
      user.id,
      dto.amountCents,
      idempotencyKey,
    );
    // Balance is unchanged until the provider confirms — the client opens
    // paymentUrl and the webhook (or mock-pay page) credits it.
    const summary = await this.billing.getSummary(user.id);
    return {
      paymentEventId,
      balanceCents: summary.balanceCents,
      paymentUrl: checkoutUrl,
      reused,
    };
  }

  @Post('subscription/checkout')
  @HttpCode(HttpStatus.OK)
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  @ApiOperation({ summary: 'Start a MOVA Plus subscription checkout' })
  subscriptionCheckout(
    @CurrentUser() user: AuthenticatedUser,
  ): Promise<{ checkoutUrl: string }> {
    return this.billing.startSubscriptionCheckout(user.id);
  }

  @Post('subscription/cancel')
  @HttpCode(HttpStatus.OK)
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  @ApiOperation({
    summary: 'Cancel auto-renewal — keep MOVA Plus until the period ends',
  })
  cancelSubscription(
    @CurrentUser() user: AuthenticatedUser,
  ): Promise<BillingSummary> {
    return this.billing.cancelSubscription(user.id);
  }

  @Public()
  @Post('webhook/wayforpay')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Payment provider webhook (signature-verified)' })
  webhook(
    @Body() payload: Record<string, unknown>,
  ): Promise<Record<string, unknown>> {
    return this.billing.handleProviderWebhook(payload);
  }

  @Public()
  @Get('mock-pay')
  @Header('content-type', 'text/html; charset=utf-8')
  @ApiOperation({ summary: 'Mock checkout page (mock provider only)' })
  async mockPay(@Query('ref') ref: string): Promise<string> {
    await this.billing.settleMock(ref ?? '');
    return "<html><body style='font-family:sans-serif;text-align:center;padding:48px'><h2>Оплачено ✅</h2><p>Дякуємо! Можете повертатися до застосунку Mova.</p></body></html>";
  }

  private parseIdempotencyKey(raw: string | undefined): string | null {
    if (!raw) return null;
    const trimmed = raw.trim();
    if (trimmed.length === 0) return null;
    if (!IDEMPOTENCY_KEY_RE.test(trimmed)) {
      throw new BadRequestException(
        'Idempotency-Key must be 1–64 printable ASCII characters',
      );
    }
    return trimmed;
  }

  @Post('subscribe')
  @HttpCode(HttpStatus.OK)
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  @ApiOperation({ summary: 'Switch to a different plan (FREE / PAID)' })
  subscribe(
    @CurrentUser() user: AuthenticatedUser,
    @Body() dto: SubscribeDto,
  ): Promise<BillingSummary> {
    return this.billing.switchPlan(user.id, dto.planCode);
  }
}

export type { PaymentEvent };
