import {
  BadRequestException,
  Body,
  Controller,
  Get,
  Headers,
  HttpCode,
  HttpStatus,
  Post,
  Query,
} from '@nestjs/common';
import { ApiBearerAuth, ApiHeader, ApiOperation, ApiTags } from '@nestjs/swagger';
import { Throttle } from '@nestjs/throttler';

import { CurrentUser, type AuthenticatedUser } from '@mova-back/shared-auth';
import type { PaymentEvent, Plan, UsageRecord } from '@mova-back/shared-database';

import { BillingService, type BillingSummary } from './billing.service';
import { SubscribeDto, TopupDto } from './dto/billing.schemas';

const IDEMPOTENCY_KEY_RE = /^[\x20-\x7E]{1,64}$/;

@ApiTags('billing')
@ApiBearerAuth()
@Controller('billing')
export class BillingController {
  constructor(private readonly billing: BillingService) {}

  @Get('me')
  @ApiOperation({ summary: 'Get current subscription + balance summary' })
  me(@CurrentUser() user: AuthenticatedUser): Promise<BillingSummary> {
    return this.billing.getSummary(user.id);
  }

  @Get('plans')
  @ApiOperation({ summary: 'List active plans available for subscription' })
  async listPlans(): Promise<{ items: Plan[] }> {
    return { items: await this.billing.listPlans() };
  }

  @Get('usage')
  @ApiOperation({ summary: 'List recent usage records (last 13 months)' })
  async listUsage(
    @CurrentUser() user: AuthenticatedUser,
    @Query('from') from?: string,
    @Query('to') to?: string,
  ): Promise<{ items: UsageRecord[] }> {
    const fromDate = from ? new Date(from) : undefined;
    const toDate = to ? new Date(to) : undefined;
    return { items: await this.billing.listUsage(user.id, fromDate, toDate) };
  }

  @Post('topup')
  @HttpCode(HttpStatus.OK)
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  @ApiOperation({
    summary: 'Fake topup — credits balance immediately (MVP, no real provider)',
  })
  @ApiHeader({
    name: 'Idempotency-Key',
    required: false,
    description:
      'Optional UUID/opaque token (≤64 printable ASCII) generated by the ' +
      'client before the first attempt. Resubmitting the same key returns ' +
      'the original PaymentEvent without re-charging.',
  })
  async topup(
    @CurrentUser() user: AuthenticatedUser,
    @Body() dto: TopupDto,
    @Headers('idempotency-key') idempotencyKeyHeader?: string,
  ): Promise<{
    paymentEventId: string;
    balanceCents: number;
    paymentUrl: null;
    reused: boolean;
  }> {
    const idempotencyKey = this.parseIdempotencyKey(idempotencyKeyHeader);
    // Require the key: a keyless top-up has no dedup, so a double-tap or a
    // network retry double-credits the wallet. The client always sends one.
    if (!idempotencyKey) {
      throw new BadRequestException(
        'Idempotency-Key header is required for top-ups',
      );
    }
    const { paymentEvent, balanceCents, reused } = await this.billing.fakeTopup(
      user.id,
      dto.amountCents,
      idempotencyKey,
    );
    return {
      paymentEventId: paymentEvent.id,
      balanceCents,
      paymentUrl: null,
      reused,
    };
  }

  private parseIdempotencyKey(raw: string | undefined): string | null {
    if (!raw) return null;
    const trimmed = raw.trim();
    if (trimmed.length === 0) return null;
    if (!IDEMPOTENCY_KEY_RE.test(trimmed)) {
      throw new BadRequestException(
        'Idempotency-Key must be 1–64 printable ASCII characters',
      );
    }
    return trimmed;
  }

  @Post('subscribe')
  @HttpCode(HttpStatus.OK)
  @Throttle({ default: { limit: 5, ttl: 60_000 } })
  @ApiOperation({ summary: 'Switch to a different plan (FREE / PAID)' })
  subscribe(
    @CurrentUser() user: AuthenticatedUser,
    @Body() dto: SubscribeDto,
  ): Promise<BillingSummary> {
    return this.billing.switchPlan(user.id, dto.planCode);
  }
}

export type { PaymentEvent };
